#!/usr/bin/env bash

#TODO: Replace with maven itself.
downloadJarFiles() {
	curl https://repo1.maven.org/maven2/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar -o jlayer.jar
	curl https://repo1.maven.org/maven2/com/googlecode/soundlibs/mp3spi/1.9.5.4/mp3spi-1.9.5.4.jar -o mp3spi.jar
	curl https://repo1.maven.org/maven2/com/googlecode/soundlibs/tritonus-share/0.3.7.4/tritonus-share-0.3.7.4.jar -o tritonus.jar
	curl https://repo1.maven.org/maven2/com/googlecode/soundlibs/jorbis/0.0.17.4/jorbis-0.0.17.4.jar -o jorbis.jar
	curl https://repo1.maven.org/maven2/com/googlecode/soundlibs/vorbisspi/1.0.3.3/vorbisspi-1.0.3.3.jar -o vorbisspi.jar
}

makeManifest() {
	mkdir -p META-INF
	{
		echo Manifest-Version: 1.0
		echo Created-By: "$1"
	}>META-INF/MANIFEST.MF
}

makeLicenseFileForExternal() {
	{
		curl https://raw.githubusercontent.com/curl/curl/master/COPYING
		echo
		echo
		curl https://raw.githubusercontent.com/libarchive/libarchive/master/COPYING
		echo
		echo
		curl https://raw.githubusercontent.com/DaveGamble/cJSON/master/LICENSE
		echo
		echo
		curl https://raw.githubusercontent.com/pdudits/soundlibs/master/jlayer/LICENSE.txt
		echo
		echo
		curl https://raw.githubusercontent.com/pdudits/soundlibs/master/jorbis/COPYING.LIB
		echo
		echo
		curl https://raw.githubusercontent.com/pdudits/soundlibs/master/mp3spi/LICENSE.txt
		echo
		echo
		curl https://raw.githubusercontent.com/pdudits/soundlibs/master/tritonus-cvs/LGPL
		echo
		echo
		curl https://raw.githubusercontent.com/pdudits/soundlibs/master/vorbisspi/LICENSE.txt
	}>LICENSE.txt
}

writeControlFile() {
	writeControlFileNoDeps $1 $2 $3 "$5"
	echo Depends: "$4">>control
}

writeControlFileNoDeps() {
	{
		echo Package: $1
		echo Version: $2
		echo Section: games
		echo Architecture: $3
		echo Maintainer: JCWasmx86
		echo Description: "$4"
	}>control
}

buildDeb() {
	echo Installed-Size: $(expr $(du -sb ../usr| cut -f -1) / 1024)>>control
	cd ../..
	find . -exec touch -t 201108231405.14 {} \;
	dpkg-deb --build $1
}

export SOURCE_DATE_EPOCH=0
export VERSION=1.5.0
if [[ -z "${EXTENSION}" ]]; then
	export EXTENSION="ogg"
fi
. "${JAVA_HOME}"/release
major=$(echo "${JAVA_VERSION}" | cut -d. -f1)
if [ "$major" == "15" ]; then
	echo Found suitable java installation
else
	echo Didn\'t find java, version 15
	exit 1
fi
if [[ $(gcc -dumpversion) =~ "10.*" ]]; then
	echo Didn\'t find gcc-10
	exit 1
else
	echo Found gcc-10
fi
export TARGET="all-gtk"
unameOut="$(uname -s)"
case "${unameOut}" in
	MINGW*)
		:
	;&
	MSYS*)
		if [[ -z "${JAVA_HOME}" ]]; then
			echo JAVA_HOME is not set\!
			exit 1
		else
			export PATH=$PATH:$(cygpath "${JAVA_HOME}")/bin:$(cygpath "C:\\Program Files\\Musescore 3\\bin")
		fi
		export TARGET="all-win"
		export IS_WIN="IS_WIN"
	;;
esac
#Check here, as we may update the path to include Musescore
if ! command -v musescore3 &> /dev/null; then
	echo Didn\'t find musescore3
	exit 1
else
	echo Found musescore
	export MUSESCORE=$(type -p musescore3)
	echo Musescore="$MUSESCORE"
fi
mkdir -p music_tmp conquer-dist/{backend/data,frontend,music,frontend/music,frontendSPI}
cd Conquer || exit
shopt -s dotglob
javac $(find src -name "*.java") -d ../conquer-dist/backend -g -parameters --enable-preview --source 15|| exit 1
cp src/org/jel/game/*properties ../conquer-dist/backend/org/jel/game/
cp src/org/jel/game/plugins/builtins/*.properties ../conquer-dist/backend/org/jel/game/plugins/builtins
cp -rv images ../conquer-dist/backend
cd ../ConquerFrontendSPI
javac $(find src -name "*.java") -d ../conquer-dist/frontendSPI --class-path=../conquer-dist/backend --module-path=../conquer-dist/backend -g -parameters --enable-preview --source 15|| exit 1
cd ../ConquerFrontend || exit
cp -rv images ../conquer-dist/frontend
javac $(find src -name "*.java") -d ../conquer-dist/frontend --class-path=../conquer-dist/backend --module-path=../conquer-dist/backend:../conquer-dist/frontendSPI -g -parameters --enable-preview --source 15|| exit 1
cp src/org/jel/gui/*.properties ../conquer-dist/frontend/org/jel/gui/
cp -rv images ../conquer-dist/frontend
cd ../ScenarioGenerator || exit
javac $(find src -name "*.java") -d bin -g -parameters|| exit 1
cp -r images bin
cd bin || exit
java --class-path=.:../images:.. org.jel.tool.Belenos|| exit 1
java --class-path=.:../images:.. org.jel.tool.Etiona|| exit 1
java --class-path=.:../images:.. org.jel.tool.Slaine|| exit 1
java --class-path=.:../images:.. org.jel.tool.Freedo|| exit 1
cd ../../conquer-dist || exit
mkdir tmp
cd backend || exit
mkdir -p META-INF/services
makeManifest $major
echo org.jel.game.plugins.builtins.ChangeCitiesMinds>META-INF/services/org.jel.game.plugins.Plugin
find . -exec touch -t 201108231405.14 {} \;
zip -X ../tmp/ChangeCitiesMinds.jar META-INF/MANIFEST.MF META-INF/services/org.jel.game.plugins.Plugin org/jel/game/plugins/builtins/ChangeCitiesMinds.class org/jel/game/plugins/builtins/ClanChangeMessage.class org/jel/game/plugins/builtins/ChangeCitiesMindsMessages.class org/jel/game/plugins/builtins/changeCitiesMinds*.properties
rm org/jel/game/plugins/builtins/ChangeCitiesMinds.class org/jel/game/plugins/builtins/ClanChangeMessage.class org/jel/game/plugins/builtins/ChangeCitiesMindsMessages.class org/jel/game/plugins/builtins/changeCitiesMinds*.properties
echo org.jel.game.plugins.builtins.DefaultMusic>META-INF/services/org.jel.game.plugins.Plugin
find . -exec touch -t 201108231405.14 {} \;
zip -X ../tmp/DefaultMusic.jar META-INF/MANIFEST.MF META-INF/services/org.jel.game.plugins.Plugin org/jel/game/plugins/builtins/DefaultMusic.class
rm org/jel/game/plugins/builtins/DefaultMusic.class
echo org.jel.game.plugins.builtins.IncreaseGrowth>META-INF/services/org.jel.game.plugins.Plugin
find . -exec touch -t 201108231405.14 {} \;
zip -X ../tmp/IncreaseGrowth.jar META-INF/MANIFEST.MF META-INF/services/org.jel.game.plugins.Plugin org/jel/game/plugins/builtins/IncreaseGrowth.class
rm org/jel/game/plugins/builtins/IncreaseGrowth.class
echo org.jel.game.plugins.builtins.MoneyAnalyzer>META-INF/services/org.jel.game.plugins.Plugin
find . -exec touch -t 201108231405.14 {} \;
zip -X ../tmp/MoneyAnalyzer.jar META-INF/MANIFEST.MF META-INF/services/org.jel.game.plugins.Plugin org/jel/game/plugins/builtins/MoneyAnalyzer.class org/jel/game/plugins/builtins/SoldiersDesertedBecauseOfMissingMoneyMessage.class org/jel/game/plugins/builtins/MoneyAnalyzerMessages.class org/jel/game/plugins/builtins/moneyAnalyzer*.properties
rm org/jel/game/plugins/builtins/MoneyAnalyzer.class org/jel/game/plugins/builtins/SoldiersDesertedBecauseOfMissingMoneyMessage.class org/jel/game/plugins/builtins/MoneyAnalyzerMessages.class org/jel/game/plugins/builtins/moneyAnalyzer*.properties
echo org.jel.game.plugins.builtins.PeriodicGrowthChange>META-INF/services/org.jel.game.plugins.Plugin
find . -exec touch -t 201108231405.14 {} \;
zip -X ../tmp/PeriodicGrowthChange.jar META-INF/MANIFEST.MF META-INF/services/org.jel.game.plugins.Plugin org/jel/game/plugins/builtins/PeriodicGrowthChange.class
rm org/jel/game/plugins/builtins/PeriodicGrowthChange.class
echo org.jel.game.plugins.builtins.ResourceAnalyzer>META-INF/services/org.jel.game.plugins.Plugin
find . -exec touch -t 201108231405.14 {} \;
zip -X ../tmp/ResourceAnalyzer.jar META-INF/MANIFEST.MF META-INF/services/org.jel.game.plugins.Plugin org/jel/game/plugins/builtins/*.class org/jel/game/plugins/builtins/*.properties
rm -rf org/jel/game/plugins/builtins/
rm META-INF/services/org.jel.game.plugins.Plugin
echo org.jel.game.strategies.SortedStrategyProvider>META-INF/services/org.jel.game.data.strategy.StrategyProvider
find . -exec touch -t 201108231405.14 {} \;
zip -X ../tmp/SortedStrategy.jar META-INF/MANIFEST.MF META-INF/services/org.jel.game.data.strategy.StrategyProvider org/jel/game/strategies/*.class
rm -rf org/jel/game/strategies/
cd ../tmp || exit
cp -v ../../ScenarioGenerator/bin/*.data ../../ScenarioGenerator/*.png .
echo "<info>" >info.xml
echo "	<scenarios>">>info.xml
echo "		<scenario name=\"Belenos\" file=\"Belenos.data\" thumbnail=\"Belenos.png\" />">>info.xml
echo "		<scenario name=\"Etiona\" file=\"Etiona.data\" thumbnail=\"Etiona.png\" />">>info.xml
echo "		<scenario name=\"Slaine\" file=\"Slaine.data\" thumbnail=\"Slaine.png\" />">>info.xml
echo "		<scenario name=\"Freedo\" file=\"Freedo.data\" thumbnail=\"Freedo.png\" />">>info.xml
echo "	</scenarios>">>info.xml
echo "	<plugins>">>info.xml
echo "		<plugin className=\"org.jel.game.plugins.builtins.ChangeCitiesMinds\" />">>info.xml
echo "		<plugin className=\"org.jel.game.plugins.builtins.IncreaseGrowth\" />">>info.xml
echo "		<plugin className=\"org.jel.game.plugins.builtins.MoneyAnalyzer\" />">>info.xml
echo "		<plugin className=\"org.jel.game.plugins.builtins.ResourceAnalyzer\" />">>info.xml
echo "		<!--<plugin className=\"org.jel.game.plugins.builtins.DefaultMusic\" />-->">>info.xml
echo "		<plugin className=\"org.jel.game.plugins.builtins.PeriodicGrowthChange\" />">>info.xml
echo "	</plugins>">>info.xml
echo "	<strategies>">>info.xml
echo "		<strategy className=\"org.jel.game.strategies.SortedStrategyProvider\" />">>info.xml
echo "	</strategies>">>info.xml
echo "	<readers>">>info.xml
echo "		<reader className=\"org.jel.game.data.ri.ScenarioFileReaderFactory\" />">>info.xml
echo "	</readers>">>info.xml
echo "</info>">>info.xml
mkdir -p .conquer/libs
mv -v *.jar .conquer/libs
mv -v *.data *.xml *.png .conquer
cd .conquer || exit
find . -exec touch -t 201108231405.14 {} \;
zip -X ../../conquer.zip -r *
cp ../../conquer.zip ../../backend/data
cd ../../../music || exit
for f in *.mscz; do
	if [[ "$f" -nt "../music_tmp/${f%.mscz}.$EXTENSION" ]]; then
		"${MUSESCORE}" -o  "../music_tmp/${f%.mscz}.$EXTENSION" "$f" &
	else
		echo Skipping conversion of "$f"
	fi
done
wait
mkdir ../conquer-dist/music
cp -v ../music_tmp/* ../conquer-dist/music
cd ../conquer-dist/backend || exit
rm -rf META-INF/
mkdir -p META-INF/services
makeManifest $major
find . -exec touch -t 201108231405.14 {} \;
zip -X -r ../Conquer_resources.jar META-INF images data
rm -r images data
echo org.jel.game.data.ri.ScenarioFileReaderFactory>META-INF/services/org.jel.game.data.ConquerInfoReaderFactory
echo org.jel.game.data.builtin.OffensiveStrategyProvider>META-INF/services/org.jel.game.data.strategy.StrategyProvider
echo org.jel.game.data.builtin.DefensiveStrategyProvider>>META-INF/services/org.jel.game.data.strategy.StrategyProvider
echo org.jel.game.data.builtin.ModerateStrategyProvider>>META-INF/services/org.jel.game.data.strategy.StrategyProvider
echo org.jel.game.data.builtin.RandomStrategyProvider>>META-INF/services/org.jel.game.data.strategy.StrategyProvider
echo org.jel.game.data.DefaultScenarioProvider>META-INF/services/org.jel.game.data.InstalledScenarioProvider
find . -exec touch -t 201108231405.14 {} \;
zip -X -r ../Conquer.jar *
cd ..
mkdir -p frontend/music
cd music || exit
cp Credits.$EXTENSION Defeated.$EXTENSION Intro.$EXTENSION MainScreen.$EXTENSION Victory.$EXTENSION ../frontend/music
rm Credits.$EXTENSION Defeated.$EXTENSION Intro.$EXTENSION MainScreen.$EXTENSION Victory.$EXTENSION
cd ..
cp conquer.zip backend/data
cd frontend || exit
rm -r META-INF
mkdir META-INF
makeManifest $major
find . -exec touch -t 201108231405.14 {} \;
zip -X -r ../Conquer_frontend_resources.jar images music META-INF
rm -r images music
zip -X -r ../Conquer_frontend.jar *
cd ../frontendSPI
rm -r META-INF
makeManifest $major
find . -exec touch -t 201108231405.14 {} \;
zip -X -r ../ConquerFrontendSPI.jar *
cd ../../Launcher || exit
make clean
make $TARGET|| exit 1
if [[ -z "${IS_WIN}" ]]; then
	cp launcher conquer_launcher ../conquer-dist
else
	cp launcher.exe ../conquer-dist
fi
cd ../conquer-dist || exit
cd music || exit
mkdir -p libs/sounds
cp *.$EXTENSION libs/sounds
find . -exec touch -t 201108231405.14 {} \;
zip -X -9 ../Music.zip libs/sounds/*.$EXTENSION
wait
cd ..
makeLicenseFileForExternal
curl https://raw.githubusercontent.com/JCWasmx86/Conquer/main/LICENSE>Conquer.license
if [[ -z "${IS_WIN}" ]]; then
	rm -r conquer
	mkdir -p conquer/usr/{bin,share/java,share/conquer}
	mkdir -p conquer/DEBIAN
	chmod 0755 conquer/DEBIAN/
	cd conquer/DEBIAN || exit
	writeControlFile conquer $VERSION $(dpkg --print-architecture) "conquer-engine, conquer-gui, libcurl4, libarchive13, libgtk-3-0" "The GUI for the strategy game conquer"
	cd ../..
	mv launcher conquer_launcher conquer/usr/bin
	cp LICENSE.txt conquer/usr/share/conquer
	cp Conquer.license conquer/usr/share/conquer
	find . -exec touch -t 201108231405.14 {} \;
	cd conquer/DEBIAN || exit
	buildDeb conquer
	rm -r conquer-engine
	mkdir -p conquer-engine/usr/{bin,share/java,share/conquer-engine}
	mkdir -p conquer-engine/DEBIAN
	chmod 0755 conquer-engine/DEBIAN
	cd conquer-engine/DEBIAN || exit
	writeControlFileNoDeps conquer-engine $VERSION all "The game engine for the strategy game conquer"
	cd ../..
	cp Conquer.jar Conquer_resources.jar ConquerFrontendSPI.jar conquer-engine/usr/share/java
	cp LICENSE.txt conquer-engine/usr/share/conquer-engine
	cd conquer-engine/DEBIAN || exit
	buildDeb conquer-engine
	rm -r conquer-gui
	mkdir -p conquer-gui/usr/{bin,share/java,share/conquer-gui,share/java/conquer}
	mkdir -p conquer-gui/DEBIAN
	chmod 0755 conquer-gui/DEBIAN
	cd conquer-gui/DEBIAN || exit
	writeControlFile conquer-gui $VERSION all "conquer-engine" "GUI for Conquer. \(Without launcher\)"
	cd ../..
	cp Conquer_frontend.jar Conquer_frontend_resources.jar conquer-gui/usr/share/java
	cp Conquer.license LICENSE.txt conquer-gui/usr/share/conquer-gui
	cd conquer-gui/usr/share/java/conquer
	downloadJarFiles
	cd ../../../../DEBIAN || exit
	buildDeb conquer-gui
else
	cp launcher.exe Conquer.jar Conquer_frontend.jar Conquer.license LICENSE.txt Conquer_resources.jar Conquer_frontend_resources.jar  ConquerFrontendSPI.jar ../Installer
	cd ../Installer || exit
	downloadJarFiles
	make clean
	make||exit
	cp Installer.exe ../conquer-dist
	cd ../conquer-dist || exit
fi
java --version>versions
gcc --version>>versions
musescore3 --version>>versions
if [[ -z "${IS_WIN}" ]]; then
	dpkg-deb --version>>versions
fi
zip --version>>versions
cd ../Launcher/cJSON || exit
git rev-parse HEAD>>../../conquer-dist/versions
cd ../../Conquer || exit
mkdir -p tmp/data
javac $(find src test -name "*.java") -d tmp -g -parameters --enable-preview --source 15|| exit 1
cp src/org/jel/game/*properties tmp/org/jel/game/
cp src/org/jel/game/plugins/builtins/*.properties tmp/org/jel/game/plugins/builtins
cp -rv images tmp
cp -rv ../conquer-dist/conquer.zip tmp/data
cd tmp || exit
#First install everything
java --enable-preview org.jel.game.testsuite.Testsuite1||exit
#Run the tests for bad arguments
java --enable-preview org.jel.game.testsuite.Testsuite2||exit
#Run the tests for saving and restoring games
#The check is there, as TestSuite3 somehow fails in the CI for windows. ("Access is denied")
if [[ ! $NO_TESTS3 ]]; then java --enable-preview org.jel.game.testsuite.Testsuite3||exit; fi
cd ..
rm -rf tmp
exit 0
