#!/usr/bin/env bash
#Assume Conquer is installed
cd Conquer
mkdir tmp
javac `find src test -name "*.java"` -d tmp --enable-preview --source 15|| exit 1
cp src/org/jel/game/*properties tmp/org/jel/game/
cp src/org/jel/game/plugins/builtins/*.properties tmp/org/jel/game/plugins/builtins
cd tmp
java --enable-preview org.jel.game.testsuite.PerformanceTest||exit
cd ..
rm -r tmp
