#!/usr/bin/sh
cd data||exit
cd ..
make -B all
ecgi ${MSYSTEM_PREFIX:1}
git -C Windows-10 pull || git clone https://github.com/B00merang-Project/Windows-10 Windows-10
mkdir -p data/share/themes/Windows10/gtk-3.0
cp -r Windows-10/gtk-3.20 data/share/themes/Windows10/gtk-3.0
wget -N https://repo.msys2.org/mingw/$MSYSTEM_CARCH/$MINGW_PACKAGE_PREFIX-adwaita-icon-theme-3.38.0-3-any.pkg.tar.zst||exit
tar -I zstd -xvf $MINGW_PACKAGE_PREFIX-adwaita-icon-theme-3.38.0-3-any.pkg.tar.zst
cp -r ${MSYSTEM_PREFIX:1}/share ${MSYSTEM_PREFIX:1}/lib data
wget -N https://repo.msys2.org/mingw/$MSYSTEM_CARCH/$MINGW_PACKAGE_PREFIX-hicolor-icon-theme-0.17-2-any.pkg.tar.zst||exit
tar -I zstd -xvf $MINGW_PACKAGE_PREFIX-hicolor-icon-theme-0.17-2-any.pkg.tar.zst
cp -r ${MSYSTEM_PREFIX:1}/share data
#Remove useless clutter
rm .BUILDINFO .INSTALL .MTREE .PKGINFO
rm -r ${MSYSTEM_PREFIX:1}
cd data||exit
#Found with trial and error
echo Prefix is: $MSYSTEM_PREFIX
cp ../conquer_launcher.exe .
cp $MSYSTEM_PREFIX/bin/libarchive-13.dll .
cp $MSYSTEM_PREFIX/bin/libatk-1.0-0.dll .
cp $MSYSTEM_PREFIX/bin/libbrotlicommon.dll .
cp $MSYSTEM_PREFIX/bin/libbrotlidec.dll .
cp $MSYSTEM_PREFIX/bin/libbz2-1.dll .
cp $MSYSTEM_PREFIX/bin/libcairo-2.dll .
cp $MSYSTEM_PREFIX/bin/libcairo-gobject-2.dll .
cp $MSYSTEM_PREFIX/bin/libcrypto-1_1-x64.dll .
cp $MSYSTEM_PREFIX/bin/libcurl-4.dll .
cp $MSYSTEM_PREFIX/bin/libdatrie-1.dll .
cp $MSYSTEM_PREFIX/bin/libepoxy-0.dll .
cp $MSYSTEM_PREFIX/bin/libexpat-1.dll .
cp $MSYSTEM_PREFIX/bin/libffi-7.dll .
cp $MSYSTEM_PREFIX/bin/libfontconfig-1.dll .
cp $MSYSTEM_PREFIX/bin/libfreetype-6.dll .
cp $MSYSTEM_PREFIX/bin/libfribidi-0.dll .
cp $MSYSTEM_PREFIX/bin/libgcc_s_seh-1.dll .
cp $MSYSTEM_PREFIX/bin/libgdk-3-0.dll .
cp $MSYSTEM_PREFIX/bin/libgdk_pixbuf-2.0-0.dll .
cp $MSYSTEM_PREFIX/bin/libgee-0.8-2.dll .
cp $MSYSTEM_PREFIX/bin/libgio-2.0-0.dll .
cp $MSYSTEM_PREFIX/bin/libglib-2.0-0.dll .
cp $MSYSTEM_PREFIX/bin/libgmodule-2.0-0.dll .
cp $MSYSTEM_PREFIX/bin/libgobject-2.0-0.dll .
cp $MSYSTEM_PREFIX/bin/libgraphite2.dll .
cp $MSYSTEM_PREFIX/bin/libgtk-3-0.dll .
cp $MSYSTEM_PREFIX/bin/libharfbuzz-0.dll .
cp $MSYSTEM_PREFIX/bin/libiconv-2.dll .
cp $MSYSTEM_PREFIX/bin/libidn2-0.dll .
cp $MSYSTEM_PREFIX/bin/libintl-8.dll .
cp $MSYSTEM_PREFIX/bin/libjson-glib-1.0-0.dll .
cp $MSYSTEM_PREFIX/bin/liblz4.dll .
cp $MSYSTEM_PREFIX/bin/liblzma-5.dll .
cp $MSYSTEM_PREFIX/bin/libnghttp2-14.dll .
cp $MSYSTEM_PREFIX/bin/libpango-1.0-0.dll .
cp $MSYSTEM_PREFIX/bin/libpangocairo-1.0-0.dll .
cp $MSYSTEM_PREFIX/bin/libpangoft2-1.0-0.dll .
cp $MSYSTEM_PREFIX/bin/libpangowin32-1.0-0.dll .
cp $MSYSTEM_PREFIX/bin/libpcre-1.dll .
cp $MSYSTEM_PREFIX/bin/libpixman-1-0.dll .
cp $MSYSTEM_PREFIX/bin/libpng16-16.dll .
cp $MSYSTEM_PREFIX/bin/libpsl-5.dll .
cp $MSYSTEM_PREFIX/bin/libssh2-1.dll .
cp $MSYSTEM_PREFIX/bin/libssl-1_1-x64.dll .
cp $MSYSTEM_PREFIX/bin/libstdc++-6.dll .
cp $MSYSTEM_PREFIX/bin/libthai-0.dll .
cp $MSYSTEM_PREFIX/bin/libunistring-2.dll .
cp $MSYSTEM_PREFIX/bin/libwinpthread-1.dll .
cp $MSYSTEM_PREFIX/bin/libzstd.dll .
cp $MSYSTEM_PREFIX/bin/zlib1.dll .
#Required to show svg,png files and so on.
mkdir -p lib/gdk-pixbuf-2.0/2.10.0/loaders/
gdk-pixbuf-query-loaders >lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
cp $MSYSTEM_PREFIX/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.dll lib/gdk-pixbuf-2.0/2.10.0/loaders/
cp $MSYSTEM_PREFIX/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.dll lib/gdk-pixbuf-2.0/2.10.0/loaders/
#Some needed schemas
mkdir -p share/glib-2.0/schemas
cp -r $MSYSTEM_PREFIX/share/glib-2.0/schemas/ share/glib-2.0/
mkdir -p etc/gtk-3.0
{
	echo \[Settings\]
	echo gtk-theme-name=Windows10
	echo gtk-font-name=Segoe UI 9
}>etc/gtk-3.0/settings.ini
export SOURCE_DATE_EPOCH=0
zip -X -9 -r ../data.zip ./*
