#!/usr/bin/sh
cd data||exit
cd ..
make -B all
git -C Windows-10 pull || git clone https://github.com/B00merang-Project/Windows-10 Windows-10
mkdir -p data/share/themes/Windows10/gtk-3.0
cp -r Windows-10/gtk-3.20 data/share/themes/Windows10/gtk-3.0
wget -N https://repo.msys2.org/mingw/$MSYSTEM_CARCH/$MSYSTEM_CHOST-adwaita-icon-theme-3.38.0-3-any.pkg.tar.zst||exit
tar -I zstd -xvf $MSYSTEM_CHOST-adwaita-icon-theme-3.38.0-3-any.pkg.tar.zst
cp -r mingw64/share mingw64/lib data
wget -N https://repo.msys2.org/mingw/$MSYSTEM_CARCH/$MSYSTEM_CHOST-hicolor-icon-theme-0.17-2-any.pkg.tar.zst||exit
tar -I zstd -xvf $MSYSTEM_CHOST-hicolor-icon-theme-0.17-2-any.pkg.tar.zst
cp -r mingw64/share data
#Remove useless clutter
rm .BUILDINFO .INSTALL .MTREE .PKGINFO
rm -r mingw64
cd data||exit
#Found with trial and error
echo Prefix is: $MSYSTEM_PREFIX
cp ../conquer_launcher.exe .
cp $MSYSTEM_PREFIX/libarchive-13.dll .
cp $MSYSTEM_PREFIX/libatk-1.0-0.dll .
cp $MSYSTEM_PREFIX/libbrotlicommon.dll .
cp $MSYSTEM_PREFIX/libbrotlidec.dll .
cp $MSYSTEM_PREFIX/libbz2-1.dll .
cp $MSYSTEM_PREFIX/libcairo-2.dll .
cp $MSYSTEM_PREFIX/libcairo-gobject-2.dll .
cp $MSYSTEM_PREFIX/libcrypto-1_1-x64.dll .
cp $MSYSTEM_PREFIX/libcurl-4.dll .
cp $MSYSTEM_PREFIX/libdatrie-1.dll .
cp $MSYSTEM_PREFIX/libepoxy-0.dll .
cp $MSYSTEM_PREFIX/libexpat-1.dll .
cp $MSYSTEM_PREFIX/libffi-7.dll .
cp $MSYSTEM_PREFIX/libfontconfig-1.dll .
cp $MSYSTEM_PREFIX/libfreetype-6.dll .
cp $MSYSTEM_PREFIX/libfribidi-0.dll .
cp $MSYSTEM_PREFIX/libgcc_s_seh-1.dll .
cp $MSYSTEM_PREFIX/libgdk-3-0.dll .
cp $MSYSTEM_PREFIX/libgdk_pixbuf-2.0-0.dll .
cp $MSYSTEM_PREFIX/libgee-0.8-2.dll .
cp $MSYSTEM_PREFIX/libgio-2.0-0.dll .
cp $MSYSTEM_PREFIX/libglib-2.0-0.dll .
cp $MSYSTEM_PREFIX/libgmodule-2.0-0.dll .
cp $MSYSTEM_PREFIX/libgobject-2.0-0.dll .
cp $MSYSTEM_PREFIX/libgraphite2.dll .
cp $MSYSTEM_PREFIX/libgtk-3-0.dll .
cp $MSYSTEM_PREFIX/libharfbuzz-0.dll .
cp $MSYSTEM_PREFIX/libiconv-2.dll .
cp $MSYSTEM_PREFIX/libidn2-0.dll .
cp $MSYSTEM_PREFIX/libintl-8.dll .
cp $MSYSTEM_PREFIX/libjson-glib-1.0-0.dll .
cp $MSYSTEM_PREFIX/liblz4.dll .
cp $MSYSTEM_PREFIX/liblzma-5.dll .
cp $MSYSTEM_PREFIX/libnghttp2-14.dll .
cp $MSYSTEM_PREFIX/libpango-1.0-0.dll .
cp $MSYSTEM_PREFIX/libpangocairo-1.0-0.dll .
cp $MSYSTEM_PREFIX/libpangoft2-1.0-0.dll .
cp $MSYSTEM_PREFIX/libpangowin32-1.0-0.dll .
cp $MSYSTEM_PREFIX/libpcre-1.dll .
cp $MSYSTEM_PREFIX/libpixman-1-0.dll .
cp $MSYSTEM_PREFIX/libpng16-16.dll .
cp $MSYSTEM_PREFIX/libpsl-5.dll .
cp $MSYSTEM_PREFIX/libssh2-1.dll .
cp $MSYSTEM_PREFIX/libssl-1_1-x64.dll .
cp $MSYSTEM_PREFIX/libstdc++-6.dll .
cp $MSYSTEM_PREFIX/libthai-0.dll .
cp $MSYSTEM_PREFIX/libunistring-2.dll .
cp $MSYSTEM_PREFIX/libwinpthread-1.dll .
cp $MSYSTEM_PREFIX/libzstd.dll .
cp $MSYSTEM_PREFIX/zlib1.dll .
#Required to show svg,png files and so on.
mkdir -p lib/gdk-pixbuf-2.0/2.10.0/loaders/
gdk-pixbuf-query-loaders >lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
cp $MSYSTEM_PREFIX/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.dll lib/gdk-pixbuf-2.0/2.10.0/loaders/
cp $MSYSTEM_PREFIX/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.dll lib/gdk-pixbuf-2.0/2.10.0/loaders/
#Some needed schemas
mkdir -p share/glib-2.0/schemas
cp -r $MSYSTEM_PREFIX/share/glib-2.0/schemas/ share/glib-2.0/
mkdir -p etc/gtk-3.0
{
	echo \[Settings\]
	echo gtk-theme-name=Windows10
	echo gtk-font-name=Segoe UI 9
}>etc/gtk-3.0/settings.ini
export SOURCE_DATE_EPOCH=0
zip -X -9 -r ../data.zip ./*
