name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-java@v1.4.3
        with:
            java-version: 15
      - uses: actions/checkout@v2
      - name: Run java 
        run: java --version
      - name: Run ls
        run: ls
      - name: Multiple commands
        run: |
          gcc --version
          make
